version: '3'
services:
  db:
    image: mongo:3.4
  backend:
    image: node:8.1.4
    volumes:
      - ./backend:/backend
    ports:
      - 3000:3000
    # se proxy  
    # environment:
    #   HTTP_PROXY: http://10.251.14.141:3128
    #   HTTPS_PROXY: http://10.251.14.141:3128
    #   NO_PROXY: '*.camara.gov.br,.camara.leg.br,es'
    command: bash -c "cd /backend && npm i && node app.js"  
  frontend:
    image: nginx:1.13
    volumes:
      - ./frontend:/usr/share/nginx/html/
    ports:
      - 8080:80