version: '3'

volumes:
  dados:

services:
  db:
    image: postgres:9.6
    volumes:
      # Volume dos dados
      - dados:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  frontend:
    image: nginx:1.13
    volumes:
      # Site
      - ./web:/usr/share/nginx/html
      # Configuração do proxy reverso
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
  app:
    image: python:3.6
    volumes:
      # Aplicação
      - ./app:/app
    working_dir: /app
    # environment:
    #   HTTP_PROXY: http://10.251.14.141:3128
    #   HTTPS_PROXY: http://10.251.14.141:3128
    #   NO_PROXY: '*.camara.gov.br,.camara.leg.br,es'
    command: bash ./app.sh